CREATE TABLE EMP
AS SELECT * FROM EMPLOYEES;

DESC EMP;

ALTER TABLE EMP
ADD STARS VARCHAR2(50);

SET SERVEROUTPUT ON;
DECLARE
V_EMPNO EMP.EMPLOYEE_ID%TYPE := 176;
V_ASTERISK EMP.STARS%TYPE;
V_SAL EMP.SALARY%TYPE;

BEGIN
SELECT NVL(ROUND(SALARY/1000),0) INTO V_SAL FROM EMP WHERE EMPLOYEE_ID = V_EMPNO;
FOR I IN REVERSE 1..V_SAL LOOP
V_ASTERISK := V_ASTERISK || '*';
DBMS_OUTPUT.PUT_LINE(V_ASTERISK);
END LOOP;
UPDATE EMP
SET STARS = V_ASTERISK
WHERE EMPLOYEE_ID = V_EMPNO;
END;
/

SELECT * FROM EMP WHERE EMPLOYEE_ID = 176;

